[tool.black]
line-length = 79
target-version = ["py310"]
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.github
    | _build
    | buck-out
    | build
    | dist
  )
)
'''

[tool.isort]
profile = "black"
combine_as_imports = true
force_grid_wrap = 0
force_sort_within_sections = true
include_trailing_comma = true
line_length = 79
multi_line_output = 3
skip_glob = []
use_parentheses = true


[tool.pytest.ini_options]
python_files = "test*.py"
norecursedirs = ".* build dist CVS _darcs {arch} *.egg *.egg-info venv docs .git appdir .tox .github"
console_output_style = "progress"
testpaths = ["pplay-pygame"]
addopts = "--numprocesses=auto --ds=api.settings --durations=5 --cov-report=term-missing --cov=."
