name: Code Quality and Deploy

on:
  push:
    branches:
      - main
      - "dependabot/**"
      - "refactor/**"
      - "feature/**"
      - "hotfix/**"
      - "chore/**"
      - "style/**"

jobs:
  code-quality:
    name: Code Quality and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: Cache pip
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: pplay-pygame
          password: ${{ secrets.PPLAY_PYGAME_API_TOKEN }}
